[package]
name = "darwaza"
description = "A simple reverse proxy with focus on OpenID Connect protocol"
version = "0.1.0"
license = "AGPL-3.0"
readme = "README.md"
authors = ["Amanjeev Sethi <aj@amanjeev.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
config = "0.9"
futures = { version = "0.3.1", features = ["compat"] }
hyper = "0.12.9"


[[bin]]
name = "darwaza"
path = "src/main.rs"