[package]
name = "darwaza"
description = "A simple reverse proxy with focus on OpenID Connect protocol"
version = "0.1.0"
license = "AGPL-3.0"
readme = "README.md"
authors = ["Amanjeev Sethi <aj@amanjeev.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
config = "0.9"
futures = "0.3.1"
serde = "1.0.104"
serde_json = "1.0.44"
tokio = { version = "0.2", features = ["full"] }


[[bin]]
name = "darwaza"
path = "src/darwaza.rs"